[package]
name = "teamech-console"
version = "0.9.0"
authors = ["Ellie D. <sporillium@gmail.com>"]

[dependencies]
teamech = { path = "../.." }
clap = "2"
pancurses = { version = "0.16", features = ["wide"] }
dirs = "1.0.3"
chrono = "0.4"
