[package]
name = "teamech-console"
version = "0.8.0"
authors = ["Ellie D. <sporillium@gmail.com>"]

[dependencies]
teamech = { path = "../.." }
clap = "2"
pancurses = "0.16"
dirs = "1.0.3"
chrono = "0.4"
